### ISSUE TITLE
Square shapes pass in 'side' as string instead of number

### ISSUE THREAD

**Issue by Igor-Gold** [capablemonkey/odb-pp-parser#3]
```
{
    "id": "346",
    "symbol": {
      "type": "square",
      "side": "70"
    },
    "x": 0.25425295,
    "y": 0.69755837,
    "net": "$$$16436"
}
```

**Comment by capablemonkey** [comment]
Whoops.  Forgot this guy.  I'm renaming the field from 'side' to 'width'.

The reason is, I've got a [whitelist](https://github.com/capablemonkey/odb-pp-parser/blob/85748eb2ee3d37e95c22aefbc0f53b625f69593e/lib/parseable.rb#L3-L3) of field names which get parsed as Floats. 

Apparently the parameter 'side' is also used in Net Points where its values are set of letters instead of numbers.  I'm trying to name record fields as close to their name in the spec, so since the name of the 'side' parameter on the Square symbol is more loosely defined than the Net Point 'side', I'm just going to rename square's side to 'width' which pretty much means the same thing.

**Comment by capablemonkey** [comment]
This is done in 92fc095
